export const workDataObjOne = {
    title1: "Serija W220",
    img1: "/images/catalog/SERIJA W220.png",
    desc1: "Model W220, projektovan za protoke manje od 150 Sm3/h i za vrednosti pritiska usisavanja gasa izmedju 2 i 16 bara, najmanji je iz spektra klipnih kompresora. Smanjene dimenzije kompresorske stanice (kontejnera) čine ga prikladnim za male benzinske pumpe ili za modularna proširenja.",
    title2: "Serija W360",
    img2: "/images/catalog/SERIJA W360.png",
    desc2: "Kompresor W360 je napravljen za protoke izmedju 150 e 600 Sm3/h i za vrednosti pritiska usisavanja gasa od 5 do 30 bara. Izuzetno kompaktan i višestran prikladan je za bilo koju vrstu primene: CNG, Biogas i Industriju.",
    title3: "Serija W680",
    img3: "/images/catalog/SERIJA W680.png",
    desc3: "Kompresor W680 je najtraženiji model zbog sposobnosti da se prilagodi najširem dijapazonu pritisaka usisavanja i protoka. Dostupan je u dve verzije: SE-tri faze prostog efekta, napravljen za vrednosti pritiska usisavanja gasa izmedju 3 i 50 bara; DE -barem jedna faza duplog efekta, napravljen za vrednosti pritiska usisavanja gasa izmedju 0,5 i 5bara. ",
    title4: "Serija W750",
    img4: "/images/catalog/SERIJA W750.png",
    desc4: "Serija W750 sastoji se od otpornih i veoma pouzdanih kompresora, namenjen za velike javne i privatne stanice i za glavne stanice za punjenje cisterni (vozila) za gas. Model W750 je posebno prikladan za upotrebe koje zahtevaju visoke protoke, izmedju 600 i 4000Sm3/h, i pritiske usisavanja od 0,5 do 50 bar. Dostupan je u dve verzije: SE (tri faze prostog efekta) i DE (barem jedna faza duplog efekta). ",
    title5: "Serija H950",
    img5: "/images/catalog/SERIJA H950.png",
    desc5: "Model H950 može da postigne protoke od 600 do 2800 Sm3/h i radi sa pritiscima usisavanja izmedju 4 i 70 bara.",
    title6: "Serija BS",
    img6: "/images/catalog/SERIJA BS.png",
    desc6: "Hidraulični monofazni kompresor je jedinica autonomne kompresije primenjena pored tradicionalnog mehaničkog kompresora kako bi povećala pritisak gasa sve do 250 bara; Postiže protoke od 400 do 1100 Sm3/h. Može biti opremljen električnim motorom snage 11 ili 18 kW. Projektivan za kontinuiranu upotrebu zahteva malo održavanje.",
    title7: "Serija BT",
    img7: "/images/catalog/SERIJA BT.png",
    desc7: "Dvofazni hidraulički kompresor može biti opremljen električnim motorom snage 22-30-37 kW i koristi se kao autonomna jedinica umesto mehaničkih kompresora. Dvofazni booster koristi se kada pritisci usisavanja prelaze 40 bara i posebno je namenjen manjim stanicama koje se napajaju iz cisterni za gas.",
    title8: "Dry Cooler",
    img8: "/images/catalog/DRY COOLER.png",
    desc8: "Dry cooler je gasno-tečni rashlađivač, obavlja hlađenje vode koja dolazi iz interfaznih izmenjivača kružnog kola gas-ulje. Može biti opremljen protivpožarnim motorima za instalacije u zonama gde postoji rizik od eksplozija. Kako bi se poboljšao učinak, smanjila potrošnja energijei zvučne emisije, dry cooler je napravljen u različitim konfiguracijama broja, dimenzija i razmeštaja ventilatora, kao i tražene snage. ",
    title9: "Skladištenje",
    img9: "/images/catalog/SKLADISTENJE.png",
    desc9: "Odmah pored kompresora postavljene su metalne boce za gas koje imaju ulogu rezervoara za akumulaciju gasa i omogućavaju da se ublaže prirodna pulsiranja koja nastaju u fazama pumpanja kompresora. Skladište se sastoji od boca kapaciteta 80 ili 140 litara u različitim kombinacijima u zavisnosti od zahteva. Boce, smeštene u unutrašnjost čeličnog okvira koji olakšava instaliranje i održavanje, mogu biti postavljene horizontalno ili vertikalno. Ostale konfiguracije su raspoložive na zahtev Klijenta.",
    title10: "Komandna tabla prioriteta",
    img10: "/images/catalog/KOMANDNA TABLA PRIORITETA.png",
    desc10: "Komandna tabla prioriteta je uglavnom smešten u skladištu koje dozvoljava punjenje u različitim nivoima pritiska. Tabla može biti instaliranai na ulaznoj liniji kompresora kako bi ga snabdevala do različitih nivoa pritiska. ",
    title11: "Kabina za merenje",
    img11: "/images/catalog/KABINA ZA MERENJE.png",
    desc11: "Kabina za merenje vrši filtraciju i merenje gasa i reguliše pritisak dostave u vrednostima koje su u skladu sa ispravnim funkcionisanjem uređaja za kompresiju i distribuciju. Projektovana je na osnovu specifičnih zahteva Klijenta.",
    title12: "Chiller",
    img12: "/images/catalog/CHILLER.png",
    desc12: "Pored uređaja za kompresiju može se instalirati dodatni rashlađivač koji, hladeći gas, omogućava snabdevanje vozila većim količinama.",
    title13: "Dryer",
    img13: "/images/catalog/DRYER.png",
    desc13: "U nekim uređajima u fazi usisavanja neophodno je instalirati sušilicu za uklanjanje vlage u gasu, koja ponekad može dostići toliki nivo da ugrozi rad kompresora. Postoje dve verzije sušilice Sicom: manualna (pojedinačni stub koji sadrži upijajući materijalsa ručnim obnavljanjem); automatska (dupli stub koji sadrži upijajući materijal sa automatskim obnavljanjem); ",
    title14: "Priključak za gas",
    img14: "/images/catalog/PRIKLJUCAK ZA GAS.png",
    desc14: "Sicom obezbeđuje liniju slavina prikladnih bilo za privatne ili javne uređaje za punjenje. Kako bi zadovoljile bilo koji radni zahtev postoje u više verzija: sa niskim ili visokim protokom, sa jednom, dve ili tri linije za punjenje, sa jednom ili dve gumene cevi za isporuku, sa električnim ili pneumatskim ventilima.",
    title15: "Kutije",
    img15: "/images/catalog/KUTIJE.png",
    desc15: "Sicom obezbeđuje različite vrste kutija u koje se smeštaju jedinice kompresora, kontejner, električna slika i ostala oprema od koje se sastoji uređaj. Dostupne su kutije od čelika ili armiranog betona i u različitim veličinama. Mogu biti zvučno izolovane i klimatizovane za ekstremne klimatske uslove. Prednja i bočna vrata omogućavaju bilo kakvu kontrolu i održavanje.",
}